name: ml-pipeline-env_py310
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.8.30=hbcca054_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgomp=14.2.0=h77fa898_1
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.47.0=hadc24fc_1
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=he02047a_1
  - openssl=3.4.0=hb9d3cd8_0
  - pip=24.3.1=pyh8b19718_0
  - python=3.10.15=h4a871b0_2_cpython
  - readline=8.2=h8228510_1
  - setuptools=75.5.0=pyhff2d567_0
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.45.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
      - annotated-types==0.7.0
      - attrs==23.2.0
      - boto3==1.35.66
      - botocore==1.35.66
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - cloudpickle==2.2.1
      - cmake==3.31.0.1
      - contourpy==1.3.1
      - cycler==0.12.1
      - dill==0.3.9
      - docker==7.1.0
      - filelock==3.16.1
      - fonttools==4.55.0
      - google-pasta==0.2.0
      - idna==3.10
      - importlib-metadata==6.11.0
      - jinja2==3.1.4
      - jmespath==1.0.1
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.7
      - lit==18.1.8
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - mock==4.0.3
      - mpmath==1.3.0
      - multiprocess==0.70.17
      - networkx==3.4.2
      - numpy==1.24.3
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.8.0.74
      - packaging==24.2
      - pandas==2.2.3
      - pathos==0.3.3
      - pillow==10.0.0
      - platformdirs==4.3.6
      - pox==0.3.5
      - ppft==1.7.6.9
      - protobuf==4.25.5
      - psutil==6.1.0
      - py-cpuinfo==9.0.0
      - pydantic==2.10.1
      - pydantic-core==2.27.1
      - pygments==2.18.0
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pyyaml==6.0.1
      - referencing==0.35.1
      - requests==2.32.3
      - rich==13.9.4
      - rpds-py==0.21.0
      - s3transfer==0.10.4
      - sagemaker==2.235.2
      - sagemaker-core==1.0.15
      - schema==0.7.7
      - scipy==1.14.1
      - seaborn==0.13.2
      - six==1.16.0
      - smdebug-rulesconfig==1.0.1
      - sympy==1.13.3
      - tblib==3.0.0
      - torch==2.0.0
      - torchvision==0.15.1
      - tqdm==4.67.0
      - triton==2.0.0
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - ultralytics==8.3.34
      - ultralytics-thop==2.0.12
      - urllib3==2.2.3
      - zipp==3.21.0
prefix: /home/sagemaker-user/.conda/envs/ml-pipeline-env_py310
